### ISSUE TITLE
Incorporar Nombre de Institución en proyectos postulados

### ISSUE THREAD

**Issue by zarria** [ANID-GITHUB/Postulaciones#1]
Es de interés conocer el nombre de la institución principal de los proyectos Postulados

**Comment by ANID-GITHUB** [comment]
Estimado,

Junto con saludar, informamos que cualquier información adicional a lo publicado en esta plataforma, deberá ser solicitada a través del portal de Transparencia, ya que los antecedentes requeridos se encuentran bajo el amparo de la Ley 20.285 sobre Transparencia en el Sector Público, y el artículo 2° letra f) de la Ley N°19.628 sobre Protección de la vida Privada. El requerimiento se tramita en la siguiente plataforma:  https://www.anid.cl/solicitud-de-informacion-ley-de-transparencia/.

Agradecemos su interés, 
Cordialmente, 

Agencia Nacional de Investigación y Desarrollo – ANID
